
import sys
from pathlib import Path

# Get project root and add to path
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

# Load environment variables from project root
from dotenv import load_dotenv
load_dotenv(project_root / ".env")

from langchain.tools import tool
from langchain.chat_models import init_chat_model

from agent.db_querying.query_courses_from_filter import query_courses_with_filters
from agent.db_querying.generate_filters import generate_filters_from_prompt

from langchain.messages import SystemMessage
from langchain.messages import HumanMessage

from langchain.agents.middleware import TodoListMiddleware

from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import StateGraph, START, END

from agent.major_scraping.build_bulletin_vector_db import create_chroma_db, load_documents_with_cache

from typing import Dict, List, Any, TypedDict, Annotated, Literal, Optional
from typing import TypedDict, NotRequired, Required, Annotated
from pydantic import BaseModel, Field, ConfigDict

from operator import add

import os
import json
import pandas as pd
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma
from langchain.agents import create_agent

from langchain_anthropic import ChatAnthropic

from langchain_community.document_loaders import PyPDFLoader


# @node 
# def profile_update(state: CourseAdvisorState) -> CourseAdvisorState:
#     """Update the user's profile based on the user's query."""
#     pass


from typing import Dict, List, Any, TypedDict, Annotated

import agent.graph.conversation_utils as conv_utils
from agent.llm_manager import LLMManager


from langchain.agents import AgentState
from langchain.agents.middleware import AgentMiddleware
from typing import Any

from langgraph.checkpoint.memory import InMemorySaver  

from langchain.agents import create_agent
from langchain.messages import HumanMessage
from langchain.agents.middleware import AgentState, before_model, after_model
from typing_extensions import NotRequired
from typing import Any
from langgraph.runtime import Runtime
from dataclasses import dataclass
from langchain.tools import tool, ToolRuntime 

openai_api_key = os.getenv("OPENAI_API_KEY")
anthropic_api_key = os.getenv("ANTHROPIC_API_KEY")

bulletin_vector_db = None
course_vector_db = None
courses_df = None

class UserProfile(AgentState):
    """User profile"""
    messages: Annotated[list, add] # = Field(default_factory=list)
    
    user_id: str
    department_of_major: str 
    major: str
    completed_courses: List[str]
    semester: int # = Field(description="The semester the user is in out of 8 semesters")
    career_goals: List[str] # = Field(default_factory=list)
    preferences: Dict[str, Any] # = Field(default_factory=dict)

@tool(description="Get the user profile")
def get_user_profile(runtime: ToolRuntime) -> UserProfile:
    """Get the user profile"""
    return runtime
    
class SearchCoursesInput(BaseModel):
    query: str = Field(description="Natural language query like 'machine learning classes on Mondays'")
    limit: int = Field(description="Number of courses to return", default=15) 
    unique_courses_flag: bool = Field(description="Flag to indicate if unique courses should be returned", default=True)

@tool(description="Vector search for courses based on the user's query that creates filters")
def search_courses(input: SearchCoursesInput) -> Dict[str, Any]:
    """Retrieve the course context from the database using the query and limit."""
    try:
        filters = generate_filters_from_prompt(input.query)
        course_results = query_courses_with_filters(
            query=input.query,
            filters=filters,
            k=input.limit,
            conversation_context="",
            unique_courses_only=input.unique_courses_flag
        )
        return {"courses": course_results, "total_count": len(course_results)}
    except Exception as e:
        print(f"Error in search_courses: {e}")
        return {"courses": [], "total_count": 0, "error": str(e)}

@tool(description="Lookup a course by course code")
def lookup_course(course_code: str) -> Dict[str, Any]:
    """Retrieve the course context from the database."""
    try:
        # just look at ./course_data/csv/2025-Spring.csv
        global courses_df
        if courses_df is None:
            csv_path = project_root / "course_data" / "csv" / "2025-Spring.csv"
            courses_df = pd.read_csv(str(csv_path))
        
        course_results = courses_df[courses_df["course_code"] == course_code].to_dict(orient="records") 
        return {"course_results": course_results}
    except Exception as e:
        print(f"Error in lookup_course: {e}")
        return {"course_results": [], "error": str(e)}


class SearchBulletinInput(BaseModel):
    agentic_query: str = Field(description="A query generated by the agent that considers user profile and preferences")
    limit: int = Field(description="Number of results to return", default=20)

@tool(description="Vector search for courses based on query")
def search_bulletin(input: SearchBulletinInput) -> Dict[str, Any]:
    """Search the major requirements"""
    try:
        global bulletin_vector_db
        persist_dir = str((Path(__file__).parent.parent / "major_scraping" / "chroma_db").resolve())
        if os.path.exists(persist_dir) and os.listdir(persist_dir):
            print("Loading existing vector database")
            embeddings = OpenAIEmbeddings()
            bulletin_vector_db = Chroma(
                persist_directory=persist_dir,
                embedding_function=embeddings
            )
        else:
            print("Creating new vector database...")
            bulletin_vector_db = create_chroma_db()
    except Exception as e:
        print(f"Error in major_search db loading: {e}")
        return {"results": [], "error": str(e)}
    
    try:
        docs = bulletin_vector_db.similarity_search(input.agentic_query, k=input.limit)  # type: ignore[union-attr]
        results = [{"page_content": d.page_content, "metadata": d.metadata} for d in docs]
        return {"results": results}
    except Exception as e:
        print(f"Error in search_bulletin: {e}")
        return {"results": [], "error": str(e)}


MAJOR_PAGE_MAPPINGS = {
    "Computer Science": [166,167,168,169]
}

@tool(description="Lookup major requirements from the bulletin")
def lookup_major(major: str) -> str:
    try:
        # First, try to get pages from the deterministic mapping
        page_numbers = MAJOR_PAGE_MAPPINGS.get(major)
        print(f"Retrieving pages {page_numbers} for {major}")

        context_chunks = []
        agent_root = Path(__file__).parent.parent
        cache_path = str((agent_root / "graph" / "__pklcache__" / "bulletin_doc_cache.pkl").resolve())
        bulletin_file_path = str((agent_root / "major_scraping" / "Bulletin_2025-2026_PDF_with_cover_page_.pdf").resolve())
        documents = load_documents_with_cache(bulletin_file_path, cache_path)
        for page_num in page_numbers:
            try:
                page_doc = documents[page_num-1]
                if page_doc:
                    context_chunks.append(
                        f"Page {page_num}:\n{page_doc.page_content}"
                    )
            except Exception as e:
                print(f"Error retrieving page {page_num}: {e}")
                continue

        if not context_chunks:
            return f"No content found for '{major}' on specified pages."

        context = "\n\n---\n\n".join(context_chunks)

        print(f"Major context: {context}")

        print(f"Retrieved {len(context_chunks)} pages for {major}")

        return (
            f"Major requirements for '{major}':\n\n"
            f"{context}\n\n"
            f"Sources: Pages {sorted(page_numbers)}"
        )
    except Exception as e:
        print(f"Error in get_major_requirements: {e}")
        return "I'm sorry, I'm having trouble getting the major requirements. Please try again."

SCHOOL_PAGE_MAPPINGS = {
    "SEAS": [8,9,10,11,12,13,14,15]
}

@tool(description="Lookup school-wide requirements from the bulletin")
def lookup_school_wide_requirements(school: str="SEAS") -> str:
    """Lookup school-wide requirements from the school requirements database."""
    try:
        page_numbers = SCHOOL_PAGE_MAPPINGS.get(school)

        if not page_numbers:
            return f"No page mapping found for school '{school}'. Available schools: {list(SCHOOL_PAGE_MAPPINGS.keys())}"

        print(f"Retrieving pages {page_numbers} for {school}")

        context_chunks = []
        agent_root = Path(__file__).parent.parent
        cache_path = str((agent_root / "graph" / "__pklcache__" / "bulletin_doc_cache.pkl").resolve())
        bulletin_file_path = str((agent_root / "major_scraping" / "Bulletin_2025-2026_PDF_with_cover_page_.pdf").resolve())
        documents = load_documents_with_cache(bulletin_file_path, cache_path)

        for page_num in page_numbers:
            try:
                page_doc = documents[page_num-1]
                if page_doc:
                    context_chunks.append(f"Page {page_num}:\n{page_doc.page_content}")
            except Exception as e:
                print(f"Error retrieving page {page_num}: {e}")
                continue

        if not context_chunks:
            return f"No content found for '{school}' on specified pages."

        context = "\n\n---\n\n".join(context_chunks)
        print(f"Retrieved {len(context_chunks)} pages for {school}")

        return (
            f"School requirements for '{school}':\n\n"
            f"{context}\n\n"
            f"Sources: Pages {sorted(page_numbers)}"
        )
    except Exception as e:
          print(f"Error in lookup_school_requirements: {e}")
          return "I'm sorry, I'm having trouble getting the school requirements. Please try again."




SYSTEM_PROMPT = """
            You are an expert Columbia University course advisor.
            Use tools when helpful. If tools return sources, cite them briefly.
            
            search_courses: Vector search for courses based on the user's query. Example query:
            - Human: Find me courses that are related to machine learning that are offered in the spring 2026 semester.

            lookup_course: CSV lookup a course by course code. Example query:
            - Human: What are the prerequisites for CS 1101?
    
            lookup_major: Document lookup for major requirements from the bulletin. Example query:
            - Human: What are the major requirements for the Computer Science major?

            search_bulletin: Vector search the school bulletin based on the your own query that is based on the user's query. Example query:
            - Human: What are the department standards for double counting in Computer Science?

            lookup_school_wide_requirements: Document lookup for school-wide requirements from the bulletin. Example query:
            - Human: What are the school-wide requirements for the Computer Science major?
            
            When planning a major, make sure to check school-wide requirements as well.
            """

def get_course_advisor_agent():
    """Create and return the course advisor agent configured with tools and memory."""
    model = ChatAnthropic(
        model="claude-sonnet-4-5-20250929",
        temperature=0.8,
        max_tokens=5000,
        timeout=60
    )
    tools = [search_courses, lookup_course, search_bulletin, lookup_major, lookup_school_wide_requirements]
    agent = create_agent(
        model=model, 
        tools=tools,
        state_schema=UserProfile,
        checkpointer=InMemorySaver(),
        # middleware=[
        #     TodoListMiddleware(),
        #     ],
        system_prompt=SYSTEM_PROMPT
    )
    return agent

if __name__ == "__main__":
    agent = get_course_advisor_agent()
    result = agent.invoke(
        {"messages": [HumanMessage(content="Help me plan my major in Computer Science.")],
        "user_id": "123",
        "department_of_major": "COMS",
        "major": "Computer Science",
        "completed_courses": ["COMS1004"],
        "semester": 3,
        "career_goals": ["Quantitative Finance"],
        "preferences": {"class_time": "early morning classes"},
        },
        {"configurable": {"thread_id": "1"}}, # in production: postgres: https://docs.langchain.com/oss/python/langchain/short-term-memory
    )


    # for chunk in agent.stream({
    #     "messages": [HumanMessage(content="Help me plan my major in Computer Science")]
    # }, stream_mode="values"):
    #     # Each chunk contains the full state at that point
    #     latest_message = chunk["messages"][-1]
    #     if latest_message.content:
    #         print(f"Agent: {latest_message.content}")
    #     elif latest_message.tool_calls:
    #         print(f"Calling tools: {[tc['name'] for tc in latest_message.tool_calls]}")

    # print(result)
    # conv_utils.dump_messages_pretty(result["messages"])

    for msg in result["messages"]:
        msg.pretty_print()




