dept_codes = {
    "African American and African Diaspora Studies": "AFAS",
    "American Studies": "AMST",
    "Ancient Studies": "ANHS",
    "Anthropology": "ANTH",
    "Archaeology": "AHUM",
    "Architecture": "ARCH",
    "Art History and Archaeology": "AHIS",
    "Astronomy": "ASTR",
    "Biological Sciences": "BIOL",
    "Business": "BUSI",
    "Chemistry": "CHEM",
    "Classics": "CLCV",
    "Cognitive Science": "COGS",
    "Comparative Literature and Society": "CPLS",
    "Computer Science": "COMS",
    "Creative Writing": "WRIT",
    "Dance": "DNCE",
    "Drama and Theatre Arts": "THTR",
    "Earth and Environmental Sciences": "EESC",
    "East Asian Languages and Cultures": "EAAS",
    "Ecology, Evolution, and Environmental Biology": "EEEB",
    "Economics": "ECON",
    "Education": "EDUC",
    "English and Comparative Literature": "ENGL",
    "Ethnicity and Race Studies": "CSER",
    "Film and Media Studies": "FILM",
    "French": "FREN",
    "Germanic Languages": "GERM",
    "History": "HIST",
    "Human Rights": "HRTS",
    "Italian": "ITAL",
    "Jazz Studies": "JAZZ",
    "Jewish Studies": "JWST",
    "Language Resource Center": "SOAR",
    "Latin American and Caribbean Studies": "CLRS",
    "Latin American and Iberian Cultures": "SPAN",
    "Linguistics": "LING",
    "Mathematics": "MATH",
    "Medieval and Renaissance Studies": "CLME",
    "Middle Eastern, South Asian, and African Studies": "MDES",
    "Music": "MUSI",
    "Philosophy": "PHIL",
    "Physical Education and Intercollegiate Athletics": "PHED",
    "Physics": "PHYS",
    "Political Science": "POLS",
    "Psychology": "PSYC",
    "Public Health": "PUBH",
    "Regional Studies": "ASCE",
    "Religion": "RELI",
    "Science and Society": "STEM",
    "Slavic Languages": "SLCL",
    "Sociology": "SOCI",
    "Statistics": "STAT",
    "Sustainable Development": "SDEV",
    "Urban Studies": "URBS",
    "Visual Arts": "VIAR",
    "Women's and Gender Studies": "WMST"
}
